<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
	  <Nullable>disable</Nullable>
	  <RootNamespace>RollPunk.Entities</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

	<ItemGroup>
		<None Remove="**/*.uid" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\RPDebug\RPDebug.csproj" />
	</ItemGroup>

</Project>
