<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<None Remove="**/*.uid" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\RPDebug\RPDebug.csproj" />
	</ItemGroup>

</Project>
